// Generated by the DSL transpiler -- do not edit (the source is the //@@dsl block below).
// Animates the character visual riding the player capsule: drives the CharacterAnimator "speed"
// parameter from the parent capsule's actual movement (position delta, so replicas animate too)
// and yaws itself to face the move direction. The capsule root is rotation-locked and owns the
// movement; this child owns the look.

struct ScriptData
{
	AnimatorComponent* animator;
	glm::vec3 lastPos = glm::vec3(0.0f, 0.0f, 0.0f);
	float speed = 0.0f;
	float yawDeg = 0.0f;
	int hasLast = 0;
};

SCRIPT_EXPORT unsigned int ScriptDataSize(void) { return sizeof(ScriptData); }
SCRIPT_EXPORT unsigned int ScriptDataLayoutId(void) { return 2973010314u; }
REGISTER_SCRIPT_DATA_SIZE()

static const OcScriptField kScriptDataFields[] = {
	{ "speed", OC_FIELD_FLOAT, (int)offsetof(ScriptData, speed), OC_FIELD_PRIVATE },
};
SCRIPT_EXPORT const OcScriptField* ScriptDataFields(int* outCount)
{ *outCount = (int)(sizeof(kScriptDataFields) / sizeof(kScriptDataFields[0])); return kScriptDataFields; }
REGISTER_SCRIPT_DATA_FIELDS()

SCRIPT_EXPORT unsigned int ScriptRequiredComponents(void) { return (1u << 2); }
REGISTER_SCRIPT_REQUIRED_COMPONENTS()

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData);

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData)
{
	Entity* capsule = nullptr;
	if ((capsule = self->parent) != nullptr)
	{
		if (deltaSeconds > 0.0f)
		{
			glm::vec3 pos = capsule->pos;
			if ((*scriptData).hasLast == 0)
			{
				(*scriptData).lastPos = pos;
				(*scriptData).hasLast = 1;
			}
			float vx = (pos.x - (*scriptData).lastPos.x) / deltaSeconds;
			float vz = (pos.z - (*scriptData).lastPos.z) / deltaSeconds;
			(*scriptData).lastPos = pos;
			float target = glm::sqrt((vx * vx) + (vz * vz));
			(*scriptData).speed += (target - (*scriptData).speed) * glm::min(1.0f, deltaSeconds * 10.0f);
			ctx->animatorSetFloat(scriptData->animator, ctx->internString("speed"), glm::min((*scriptData).speed / 8.0f, 2.0f));
			if ((*scriptData).speed > 0.5f)
			{
				float targetYaw = glm::degrees(glm::atan(vx, vz));
				(*scriptData).yawDeg = ocMoveTowardsAngle((*scriptData).yawDeg, targetYaw, 720.0f * deltaSeconds);
			}
			self->rot = glm::quat(glm::radians(glm::vec3(0.0f, (*scriptData).yawDeg, 0.0f)));
		}
	}
}

REGISTER_UPDATE()

//@@dsl 1
//@@require AnimatorComponent
//@@data vec3 lastPos
//@@data private float speed
//@@data float yawDeg
//@@data int hasLast
//@
//@function Update(float deltaSeconds)
//@	ifexist Entity capsule in self.parent
//@		if deltaSeconds > 0
//@			vec3 pos = capsule.pos
//@			if self.data.hasLast == 0
//@				self.data.lastPos = pos
//@				self.data.hasLast = 1
//@			end
//@			float vx = (pos.x - self.data.lastPos.x) / deltaSeconds
//@			float vz = (pos.z - self.data.lastPos.z) / deltaSeconds
//@			self.data.lastPos = pos
//@			float target = math.sqrt(float x = (vx * vx) + (vz * vz))
//@			self.data.speed += (target - self.data.speed) * math.min(float a = 1, float b = deltaSeconds * 10)
//@			self.animator.setFloat(string name = "speed", float value = math.min(float a = self.data.speed / 8, float b = 2))
//@			if self.data.speed > 0.5
//@				float targetYaw = math.atan2(float y = vx, float x = vz)
//@				self.data.yawDeg = math.moveTowardsAngle(float currentDeg = self.data.yawDeg, float targetDeg = targetYaw, float maxDelta = 720 * deltaSeconds)
//@			end
//@			self.rot = math.quatFromEuler(vec3 eulerDeg = vec3(0, self.data.yawDeg, 0))
//@		end
//@	end
//@end
//@
//@@end
