// Generated by the DSL transpiler -- do not edit (the source is the //@@dsl block below).

struct ScriptData
{
	PhysicsComponent* physics;
	int num = 0;
	VrArray list = 0;
};

SCRIPT_EXPORT unsigned int ScriptDataSize(void) { return sizeof(ScriptData); }
SCRIPT_EXPORT unsigned int ScriptDataLayoutId(void) { return 2407474620u; }
REGISTER_SCRIPT_DATA_SIZE()

static const VrScriptField kScriptDataFields[] = {
	{ "num", VR_FIELD_INT, (int)offsetof(ScriptData, num), VR_FIELD_PRIVATE },
};
SCRIPT_EXPORT const VrScriptField* ScriptDataFields(int* outCount)
{ *outCount = (int)(sizeof(kScriptDataFields) / sizeof(kScriptDataFields[0])); return kScriptDataFields; }
REGISTER_SCRIPT_DATA_FIELDS()

SCRIPT_EXPORT unsigned int ScriptRequiredComponents(void) { return (1u << 3); }
REGISTER_SCRIPT_REQUIRED_COMPONENTS()

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void OnDestroy(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void OnEvent(const ScriptContext* ctx, Entity* self, int eventIdx, ScriptData* scriptData);
SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData);
static void test(const ScriptContext* ctx, Entity* self, ScriptData* scriptData, int awa);

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{
	ctx->logf(ctx->internString("OnSpawn dsl"));
}

REGISTER_ON_SPAWN()

SCRIPT_EXPORT void OnDestroy(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{
	ctx->logf(ctx->internString("OnDestroy dsl"));
}

REGISTER_ON_DESTROY()

SCRIPT_EXPORT void OnEvent(const ScriptContext* ctx, Entity* self, int eventIdx, ScriptData* scriptData)
{
	if (eventIdx == 0)
	{
		ctx->logf(ctx->internString("OnHit dsl"));
	}
}

SCRIPT_EXPORT int ScriptEventCount(void) { return 1; }
SCRIPT_EXPORT const char* ScriptEventName(int eventIdx)
{
	switch (eventIdx)
	{
		case 0: return "OnHit";
		default: return "";
	}
}

REGISTER_ON_EVENT()

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData)
{
	for (int i = 0; i < (*scriptData).num; i += 1)
	{
		ctx->physicsSetVelocity(scriptData->physics, glm::vec3(0.0f, 1.0f, 0.0f));
	}
	test(ctx, self, scriptData, 123);
}

REGISTER_UPDATE()

static void test(const ScriptContext* ctx, Entity* self, ScriptData* scriptData, int awa)
{
	if (int* vrPtr1 = static_cast<int*>(ctx->arrayElem((*scriptData).list, 0, (int)sizeof(int))))
	{
		int& j = *vrPtr1;
		j = awa;
	}

	const auto vrIter2 = ctx->arraySpan((*scriptData).list, (int)sizeof(int));
	for (int vrIdx0 = 0, vrIdx0End = vrIter2.count; vrIdx0 < vrIdx0End; ++vrIdx0)
	{
		int& k = static_cast<int*>(vrIter2.data)[vrIdx0];
		k = awa;
	}

	const auto vrIter3 = ctx->arraySpan((*scriptData).list, (int)sizeof(int));
	for (int vrIdx0 = 0, vrIdx0End = vrIter3.count; vrIdx0 < vrIdx0End; ++vrIdx0)
	{
		int& l = static_cast<int*>(vrIter3.data)[vrIdx0];
		l = 42;
	}
}

//@@dsl 1
//@@require PhysicsComponent
//@@data private int num
//@@data int[] list
//@@event OnHit
//@
//@function OnSpawn()
//@	printf(string format = "OnSpawn dsl")
//@end
//@
//@function OnDestroy()
//@	printf(string format = "OnDestroy dsl")
//@end
//@
//@function OnEvent(int eventIdx)
//@	if eventIdx == self.events.OnHit
//@		printf(string format = "OnHit dsl")
//@	end
//@end
//@
//@function Update(float deltaSeconds)
//@	for int i = 0, i < self.data.num, i += 1
//@		self.physics.setVelocity(vec3 velocity = vec3(0, 1, 0))
//@	end
//@	test(int awa = 123)
//@end
//@
//@function test(int awa)
//@	ifexist ref int j in self.data.list at 0
//@		ref j = awa
//@	end
//@	
//@	foreach ref int k in self.data.list
//@		ref k = awa
//@	end
//@	
//@	foreach ref int l in self.data.list
//@		ref l = 42
//@	end
//@end
//@
//@@end
