// Generated by the DSL transpiler -- do not edit (the source is the //@@dsl block below).

struct ScriptData
{
	SceneComponent* scene;
	PhysicsComponent* physics;
	int num = 0;
	VrArray list = 0;
};

SCRIPT_EXPORT unsigned int ScriptDataSize(void) { return sizeof(ScriptData); }
SCRIPT_EXPORT unsigned int ScriptDataLayoutId(void) { return 3713242634u; }
REGISTER_SCRIPT_DATA_SIZE()

SCRIPT_EXPORT unsigned int ScriptRequiredComponents(void) { return (1u << 0) | (1u << 3); }
REGISTER_SCRIPT_REQUIRED_COMPONENTS()

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void OnDestroy(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void OnEvent(const ScriptContext* ctx, Entity* self, int eventIdx, ScriptData* scriptData);
SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData);
static bool test(const ScriptContext* ctx, Entity* self, ScriptData* scriptData, float& a);

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{
	ctx->log(ctx->internString("OnSpawn dsl"));
}

REGISTER_ON_SPAWN()

SCRIPT_EXPORT void OnDestroy(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{
	ctx->log(ctx->internString("OnDestroy dsl"));
}

REGISTER_ON_DESTROY()

SCRIPT_EXPORT void OnEvent(const ScriptContext* ctx, Entity* self, int eventIdx, ScriptData* scriptData)
{
	if (eventIdx == 0)
	{
		ctx->log(ctx->internString("OnHit dsl"));
	}
}

SCRIPT_EXPORT int ScriptEventCount(void) { return 1; }
SCRIPT_EXPORT const char* ScriptEventName(int eventIdx)
{
	switch (eventIdx)
	{
		case 0: return "OnHit";
		default: return "";
	}
}

REGISTER_ON_EVENT()

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData)
{
	for (int i = 0; i < (*scriptData).num; i += 1)
	{
		ctx->physicsSetVelocity(scriptData->physics, glm::vec3(0.0f, 1.0f, 0.0f));
	}
	for (int vrIdx0 = 0, vrIdx0End = ctx->sceneGetChildCount(scriptData->scene); vrIdx0 < vrIdx0End; ++vrIdx0)
	{
		Entity* e = ctx->sceneGetChildAt(scriptData->scene, vrIdx0);
		ctx->physicsApplyImpulse(scriptData->physics, glm::vec3(1.0f, 2.0f, 3.0f));
	}
	float f = deltaSeconds;
	vrArrPush<int>(ctx, self, &(*scriptData).list, 1, 5);
}

REGISTER_UPDATE()

static bool test(const ScriptContext* ctx, Entity* self, ScriptData* scriptData, float& a)
{
	a *= 2.0f;
	return true;
}

//@@dsl 1
//@@require PhysicsComponent, SceneComponent
//@@data int num
//@@data int[] list
//@@event OnHit
//@
//@function OnSpawn()
//@	print(string message = "OnSpawn dsl")
//@end
//@
//@function OnDestroy()
//@	print(string message = "OnDestroy dsl")
//@end
//@
//@function OnEvent(int eventIdx)
//@	if eventIdx == self.events.OnHit
//@		print(string message = "OnHit dsl")
//@	end
//@end
//@
//@function Update(float deltaSeconds)
//@	for int i = 0, i < self.data.num, i += 1
//@		self.physics.setVelocity(vec3 velocity = vec3(0, 1, 0))
//@	end
//@	foreach Entity e in self.scene.getChildren()
//@		e.physics.applyImpulse(vec3 impulse = vec3(1, 2, 3))
//@	end
//@	float f = deltaSeconds
//@	self.data.list.push(int value = 5)
//@end
//@
//@function test(ref float a) -> bool
//@	ref a *= 2
//@	return true
//@end
//@
//@@end
